"""create_bus_campus_full_schema

Revision ID: f51897ab97a4
Revises: 
Create Date: 2026-07-20 00:09:01.146629

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51897ab97a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bus_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fare_amount', sa.Integer(), nullable=False),
    sa.Column('is_Active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_lines_name'), 'bus_lines', ['name'], unique=False)
    op.create_index(op.f('ix_bus_lines_org_id'), 'bus_lines', ['org_id'], unique=False)
    op.create_table('gateway_phones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('operateur', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('student_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_org_id'), 'student', ['org_id'], unique=False)
    op.create_index(op.f('ix_student_phone_e164'), 'student', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_student_student_number'), 'student', ['student_number'], unique=False)
    op.create_table('bus_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['bus_lines.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_stops_line_id'), 'bus_stops', ['line_id'], unique=False)
    op.create_index(op.f('ix_bus_stops_org_id'), 'bus_stops', ['org_id'], unique=False)
    op.create_table('device_finger_print',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('device_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_finger_print_student_id'), 'device_finger_print', ['student_id'], unique=False)
    op.create_table('gateway_sms_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gateway_id', sa.Uuid(), nullable=False),
    sa.Column('sms_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway_phones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_sms_queue_gateway_id'), 'gateway_sms_queue', ['gateway_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('bus_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['bus_lines.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_bus_id'), 'trips', ['bus_id'], unique=False)
    op.create_index(op.f('ix_trips_scheduled_arrival'), 'trips', ['scheduled_arrival'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('balance_minor_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_wallets_org_id'), 'wallets', ['org_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('boarding_stop_id', sa.Uuid(), nullable=True),
    sa.Column('alighting_stop_id', sa.Uuid(), nullable=True),
    sa.Column('device_finger_print', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alighting_stop_id'], ['bus_stops.id'], ),
    sa.ForeignKeyConstraint(['boarding_stop_id'], ['bus_stops.id'], ),
    sa.ForeignKeyConstraint(['device_finger_print'], ['device_finger_print.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['bus_lines.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('totp_secret')
    )
    op.create_index(op.f('ix_tickets_device_finger_print'), 'tickets', ['device_finger_print'], unique=False)
    op.create_index(op.f('ix_tickets_line_id'), 'tickets', ['line_id'], unique=False)
    op.create_index(op.f('ix_tickets_org_id'), 'tickets', ['org_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_student_id'), 'tickets', ['student_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('balance_after_minor_units', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('operateur', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_wallet_transactions_org_id'), 'wallet_transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_student_id'), 'wallet_transactions', ['student_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_student_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_org_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_tickets_student_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_org_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_line_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_device_finger_print'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_wallets_org_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_trips_scheduled_arrival'), table_name='trips')
    op.drop_index(op.f('ix_trips_bus_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_gateway_sms_queue_gateway_id'), table_name='gateway_sms_queue')
    op.drop_table('gateway_sms_queue')
    op.drop_index(op.f('ix_device_finger_print_student_id'), table_name='device_finger_print')
    op.drop_table('device_finger_print')
    op.drop_index(op.f('ix_bus_stops_org_id'), table_name='bus_stops')
    op.drop_index(op.f('ix_bus_stops_line_id'), table_name='bus_stops')
    op.drop_table('bus_stops')
    op.drop_index(op.f('ix_student_student_number'), table_name='student')
    op.drop_index(op.f('ix_student_phone_e164'), table_name='student')
    op.drop_index(op.f('ix_student_org_id'), table_name='student')
    op.drop_table('student')
    op.drop_table('gateway_phones')
    op.drop_index(op.f('ix_bus_lines_org_id'), table_name='bus_lines')
    op.drop_index(op.f('ix_bus_lines_name'), table_name='bus_lines')
    op.drop_table('bus_lines')
    op.drop_table('organizations')
    op.drop_table('buses')
    # ### end Alembic commands ###
