"""adding payment table

Revision ID: fdbe189ec625
Revises: 2e64c4689063
Create Date: 2026-08-10 11:25:35.480593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fdbe189ec625'
down_revision: Union[str, Sequence[str], None] = '2e64c4689063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('students_id', sa.Uuid(), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('refund_of_payment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['refund_of_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['students_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_org_id'), 'payments', ['org_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_payments_students_id'), 'payments', ['students_id'], unique=False)
    op.create_index(op.f('ix_payments_ticket_id'), 'payments', ['ticket_id'], unique=False)
    op.add_column('api-keys', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('api-keys', 'expire_at')
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_tokens', 'expire_at')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_verfied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verfied', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'is_verified')
    op.add_column('refresh_tokens', sa.Column('expire_at', sa.DATETIME(), nullable=False))
    op.drop_column('refresh_tokens', 'expires_at')
    op.add_column('api-keys', sa.Column('expire_at', sa.DATETIME(), nullable=False))
    op.drop_column('api-keys', 'expires_at')
    op.drop_index(op.f('ix_payments_ticket_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_students_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_org_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
